### ISSUE TITLE
CI/CD Tool Integration

### ISSUE THREAD

**Issue by tremainebuchanan** [tremainebuchanan/mail-mgmt-app#12]
A continuous integration/delivery tool such as Travis CI could be configured to ensure tests are ran prior to the code being merged into branches.

**Comment by sowmiyamuthuraman** [comment]
Can I work on this?

**Comment by cakhanif** [comment]
> 
> 
> A continuous integration/delivery tool such as Travis CI could be configured to ensure tests are ran prior to the code being merged into branches.

#13

**Comment by cakhanif** [comment]
> 
> 
> > A continuous integration/delivery tool such as Travis CI could be configured to ensure tests are ran prior to the code being merged into branches.
> 
> #13

I have added .travis.yml

**Comment by tremainebuchanan** [comment]
Issue now closed through PR #16
