### ISSUE TITLE
Docker File Creation

### ISSUE THREAD

**Issue by tremainebuchanan** [tremainebuchanan/mail-mgmt-app#15]
To ensure that persons are able to download the repository locally and start developing with minimal setup, a docker file or image can be created.

**Comment by cakhanif** [comment]
i'll take this one

**Comment by cakhanif** [comment]
> 
> 
> To ensure that persons are able to download the repository locally and start developing with minimal setup, a docker file or image can be created.

#16

**Comment by tremainebuchanan** [comment]
Reviewed and closed through PR #16
